    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        access_log  /var/log/nginx/access.log;
        error_log   /var/log/nginx/error.log;

        proxy_connect_timeout 60s;
        proxy_send_timeout    60s;
        proxy_read_timeout    60s;
        client_max_body_size  10M;

    
        upstream api_principal {
            server backend:3001;
        }

    
        server {
            listen 80;
            server_name edulibre.local;

            return 301 https://$host$request_uri;
        }

    
        server {
            listen 443 ssl;
            server_name edulibre.local;


            ssl_certificate     /etc/nginx/certs/edulibre.local.pem;
            ssl_certificate_key /etc/nginx/certs/edulibre.local-key.pem;

            ssl_protocols       TLSv1.2 TLSv1.3;
            ssl_ciphers         HIGH:!aNULL:!MD5;
            ssl_prefer_server_ciphers on;


            add_header X-Frame-Options            "SAMEORIGIN"                       always;
            add_header X-Content-Type-Options     "nosniff"                          always;
            add_header Referrer-Policy            "strict-origin-when-cross-origin"  always;
            add_header Content-Security-Policy    "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;" always;
            add_header Strict-Transport-Security  "max-age=31536000; includeSubDomains" always;

            location /nginx-health {
                access_log off;
                return 200 "Nginx OK\n";
                add_header Content-Type text/plain;
            }


            location /api/ {
                rewrite ^/api/(.*) /$1 break;
                proxy_pass         http://api_principal;
                proxy_http_version 1.1;
                proxy_set_header   Host              $host;
                proxy_set_header   X-Real-IP         $remote_addr;
                proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto $scheme;
                proxy_set_header   X-Forwarded-Host  $server_name;
            }

    
            location / {
                root  /usr/share/nginx/html;
                index index.html;

                try_files $uri $uri/ /index.html;
            }


            error_page 404 /404.json;
            location = /404.json {
                return 404 '{"error":"Rota não encontrada"}\n';
                add_header Content-Type application/json;
            }

            error_page 502 503 504 /50x.json;
            location = /50x.json {
                return 502 '{"error":"Serviço temporariamente indisponível"}\n';
                add_header Content-Type application/json;
            }
        }
    }